# Dummy config file for AnyaWallet

[wallet]
wallet_type = "Standard"
network = "Testnet"
name = "anya-wallet"
seed_phrase = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
password = "password"
receive_descriptor = ""
change_descriptor = ""
xpub = ""
data_dir = "./"
use_rpc = false
coin_selection = "LargestFirst"
gap_limit = 20
min_confirmations = 1
fee_strategy = "Medium"

[bitcoin_client]
client_type = "electrum"
url = "ssl://electrum.blockstream.info:60002"
